# Generated by Django 3.2.6 on 2022-06-27 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('iban', models.UUIDField(default=uuid.UUID('186f5822-878f-49a9-bd84-9f4216187a77'), primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BankCustomer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('54ba1e26-5580-4376-bde5-0ce7a9826176'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('card_number', models.PositiveSmallIntegerField(max_length=16, primary_key=True, serialize=False)),
                ('exp_date', models.DateField(default=datetime.date(2026, 6, 27))),
                ('cvv_code', models.PositiveSmallIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.bankaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.bankcustomer')),
            ],
        ),
    ]
