# Generated by Django 3.2.6 on 2022-06-27 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20220627_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.UUIDField(default=uuid.UUID('e00662a6-e707-4200-83ab-6c66fef19a3f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='card_number',
            field=models.PositiveBigIntegerField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankcustomer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('50f9c3cc-0210-47e3-97c0-be0a150e0c0e'), primary_key=True, serialize=False),
        ),
    ]
