# Generated by Django 4.1 on 2022-08-09 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import plan.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('started_at', models.DateField(default=datetime.date.today)),
                ('finished_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('is waiting', 'IS_WAITING'), ('in progress', 'IN_PROGRESS'), ('finished', 'FINISHED'), ('expired', 'EXPIRED'), ('blocked', 'BLOCKED')], default=plan.models.Status['IN_PROGRESS'], max_length=20)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.event')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
