# Generated by Django 4.0.5 on 2022-07-01 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('iban', models.UUIDField(default=uuid.UUID('c52094dc-82ce-46f7-9618-54c285d4bd75'), primary_key=True, serialize=False)),
                ('sum', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('uuid', models.UUIDField(default=uuid.UUID('53bb4abc-4c2f-4c7f-9045-1c611c6eadfa'), primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(max_length=16)),
                ('expiration_date', models.DateField(default=datetime.date(2025, 7, 1))),
                ('cvv', models.IntegerField(max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.account')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.user')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
