# Generated by Django 4.0.5 on 2022-07-01 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('iban', models.UUIDField(default=uuid.UUID('198fb542-5ea9-4a3f-b82b-5ecc45664d72'), primary_key=True, serialize=False)),
                ('sum', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('uuid', models.UUIDField(default=uuid.UUID('52e6c374-1d6d-4904-85ac-cdc04fc08780'), primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('expiration_date', models.DateField(default=datetime.date(2025, 7, 1))),
                ('cvv', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.account')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.user')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
