# Generated by Django 4.0.5 on 2022-06-29 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_score',
            fields=[
                ('iban', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=124)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank_cards',
            fields=[
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('exp_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.bank_score')),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.users')),
            ],
        ),
    ]
