# Generated by Django 4.0.6 on 2022-07-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.event'),
        ),
    ]
