# Generated by Django 4.0.6 on 2022-07-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturers',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
