# Generated by Django 4.0.6 on 2022-07-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='teg',
        ),
        migrations.AddField(
            model_name='product',
            name='teg',
            field=models.ManyToManyField(to='products.teg'),
        ),
    ]
