# Generated by Django 4.0.5 on 2022-06-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('iban', models.UUIDField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('end_date', models.DateField(auto_now=True)),
                ('cvv', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.customer')),
            ],
        ),
    ]
