# Generated by Django 4.0.6 on 2022-07-20 20:01

from django.db import migrations, models
import plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('is waiting', 'IS_WAITING'), ('in progress', 'IN_PROGRESS'), ('finished', 'FINISHED'), ('expired', 'EXPIRED'), ('bliocked', 'BLOCKED')], default=plan.models.Status['IN_PROGRESS'], max_length=20),
        ),
    ]
